# Site settings
title: Geekking blog
email: geektimelin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/pinlocation" # the subpath of your site, e.g. /blog/
url: "http://geekking.github.io" # the base hostname & protocol for your site
twitter_username: Mude Lin
github_username:  Geekking

# Build settings
markdown: kramdown


