# Site settings
title: Geekking blog
email: geektimelin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Welcome to my project Blog. Donate
baseurl: "/pinlocation" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: Geekking
github_username:  Geekking
weibo_username:  mudelin

# Build settings
markdown: kramdown


